import type { Metadata } from "next";
import "./globals.css";
import Header from "./common/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased relative bg-white text-black`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
